/*
 * Webhooks API
 *  Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage. Use webhook subscriptions to subscribe to different webhook events. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WebhookEventType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateWebhookSubscriptionRequest
 */
public class CreateWebhookSubscriptionRequestTest {
    private final CreateWebhookSubscriptionRequest model = new CreateWebhookSubscriptionRequest();

    /**
     * Model tests for CreateWebhookSubscriptionRequest
     */
    @Test
    public void testCreateWebhookSubscriptionRequest() {
        // TODO: test CreateWebhookSubscriptionRequest
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'eventTypes'
     */
    @Test
    public void eventTypesTest() {
        // TODO: test eventTypes
    }

}
