/*
 * Webhooks API
 *  Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage. Use webhook subscriptions to subscribe to different webhook events. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpensePaymentStatus;
import com.konfigthis.client.model.ExpensePaymentStatusUpdatedEventAmount;
import com.konfigthis.client.model.ExpensePaymentType;
import com.konfigthis.client.model.WebhookEventType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpensePaymentStatusUpdatedEvent
 */
public class ExpensePaymentStatusUpdatedEventTest {
    private final ExpensePaymentStatusUpdatedEvent model = new ExpensePaymentStatusUpdatedEvent();

    /**
     * Model tests for ExpensePaymentStatusUpdatedEvent
     */
    @Test
    public void testExpensePaymentStatusUpdatedEvent() {
        // TODO: test ExpensePaymentStatusUpdatedEvent
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'expenseId'
     */
    @Test
    public void expenseIdTest() {
        // TODO: test expenseId
    }

    /**
     * Test the property 'paymentStatus'
     */
    @Test
    public void paymentStatusTest() {
        // TODO: test paymentStatus
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'paymentDescription'
     */
    @Test
    public void paymentDescriptionTest() {
        // TODO: test paymentDescription
    }

    /**
     * Test the property 'cardId'
     */
    @Test
    public void cardIdTest() {
        // TODO: test cardId
    }

}
