/*
 * Webhooks API
 *  Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage. Use webhook subscriptions to subscribe to different webhook events. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpensePaymentStatus;
import com.konfigthis.client.model.ExpensePaymentStatusUpdatedEventAmount;
import com.konfigthis.client.model.ExpensePaymentType;
import com.konfigthis.client.model.WebhookEventType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The webhook will be sent when an expense payment changes status. Account must be on Brex Empower to receive these events. Subscription must be registered with a user with the CARD_ADMIN role.
 */
@ApiModel(description = "The webhook will be sent when an expense payment changes status. Account must be on Brex Empower to receive these events. Subscription must be registered with a user with the CARD_ADMIN role.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ExpensePaymentStatusUpdatedEvent {
  public static final String SERIALIZED_NAME_EVENT_TYPE = "event_type";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  private WebhookEventType eventType;

  public static final String SERIALIZED_NAME_EXPENSE_ID = "expense_id";
  @SerializedName(SERIALIZED_NAME_EXPENSE_ID)
  private String expenseId;

  public static final String SERIALIZED_NAME_PAYMENT_STATUS = "payment_status";
  @SerializedName(SERIALIZED_NAME_PAYMENT_STATUS)
  private ExpensePaymentStatus paymentStatus;

  public static final String SERIALIZED_NAME_PAYMENT_TYPE = "payment_type";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TYPE)
  private ExpensePaymentType paymentType;

  public static final String SERIALIZED_NAME_COMPANY_ID = "company_id";
  @SerializedName(SERIALIZED_NAME_COMPANY_ID)
  private String companyId;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private ExpensePaymentStatusUpdatedEventAmount amount;

  public static final String SERIALIZED_NAME_PAYMENT_DESCRIPTION = "payment_description";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DESCRIPTION)
  private String paymentDescription;

  public static final String SERIALIZED_NAME_CARD_ID = "card_id";
  @SerializedName(SERIALIZED_NAME_CARD_ID)
  private String cardId;

  public ExpensePaymentStatusUpdatedEvent() {
  }

  public ExpensePaymentStatusUpdatedEvent eventType(WebhookEventType eventType) {
    
    
    
    
    this.eventType = eventType;
    return this;
  }

   /**
   * Get eventType
   * @return eventType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public WebhookEventType getEventType() {
    return eventType;
  }


  public void setEventType(WebhookEventType eventType) {
    
    
    
    this.eventType = eventType;
  }


  public ExpensePaymentStatusUpdatedEvent expenseId(String expenseId) {
    
    
    
    
    this.expenseId = expenseId;
    return this;
  }

   /**
   * Get expenseId
   * @return expenseId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getExpenseId() {
    return expenseId;
  }


  public void setExpenseId(String expenseId) {
    
    
    
    this.expenseId = expenseId;
  }


  public ExpensePaymentStatusUpdatedEvent paymentStatus(ExpensePaymentStatus paymentStatus) {
    
    
    
    
    this.paymentStatus = paymentStatus;
    return this;
  }

   /**
   * Get paymentStatus
   * @return paymentStatus
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ExpensePaymentStatus getPaymentStatus() {
    return paymentStatus;
  }


  public void setPaymentStatus(ExpensePaymentStatus paymentStatus) {
    
    
    
    this.paymentStatus = paymentStatus;
  }


  public ExpensePaymentStatusUpdatedEvent paymentType(ExpensePaymentType paymentType) {
    
    
    
    
    this.paymentType = paymentType;
    return this;
  }

   /**
   * Get paymentType
   * @return paymentType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ExpensePaymentType getPaymentType() {
    return paymentType;
  }


  public void setPaymentType(ExpensePaymentType paymentType) {
    
    
    
    this.paymentType = paymentType;
  }


  public ExpensePaymentStatusUpdatedEvent companyId(String companyId) {
    
    
    
    
    this.companyId = companyId;
    return this;
  }

   /**
   *  This is the &#x60;id&#x60; returned in the [Get Company](https://developer.brex.com/openapi/webhooks_api/) endpoint. You can use the &#x60;company_id&#x60; to determine which access token to use when you get the details from our API endpoints. 
   * @return companyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = " This is the `id` returned in the [Get Company](https://developer.brex.com/openapi/webhooks_api/) endpoint. You can use the `company_id` to determine which access token to use when you get the details from our API endpoints. ")

  public String getCompanyId() {
    return companyId;
  }


  public void setCompanyId(String companyId) {
    
    
    
    this.companyId = companyId;
  }


  public ExpensePaymentStatusUpdatedEvent amount(ExpensePaymentStatusUpdatedEventAmount amount) {
    
    
    
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpensePaymentStatusUpdatedEventAmount getAmount() {
    return amount;
  }


  public void setAmount(ExpensePaymentStatusUpdatedEventAmount amount) {
    
    
    
    this.amount = amount;
  }


  public ExpensePaymentStatusUpdatedEvent paymentDescription(String paymentDescription) {
    
    
    
    
    this.paymentDescription = paymentDescription;
    return this;
  }

   /**
   * The name of the card acceptor.
   * @return paymentDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the card acceptor.")

  public String getPaymentDescription() {
    return paymentDescription;
  }


  public void setPaymentDescription(String paymentDescription) {
    
    
    
    this.paymentDescription = paymentDescription;
  }


  public ExpensePaymentStatusUpdatedEvent cardId(String cardId) {
    
    
    
    
    this.cardId = cardId;
    return this;
  }

   /**
   * The ID of the card that is associated with the expense.
   * @return cardId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the card that is associated with the expense.")

  public String getCardId() {
    return cardId;
  }


  public void setCardId(String cardId) {
    
    
    
    this.cardId = cardId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExpensePaymentStatusUpdatedEvent instance itself
   */
  public ExpensePaymentStatusUpdatedEvent putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpensePaymentStatusUpdatedEvent expensePaymentStatusUpdatedEvent = (ExpensePaymentStatusUpdatedEvent) o;
    return Objects.equals(this.eventType, expensePaymentStatusUpdatedEvent.eventType) &&
        Objects.equals(this.expenseId, expensePaymentStatusUpdatedEvent.expenseId) &&
        Objects.equals(this.paymentStatus, expensePaymentStatusUpdatedEvent.paymentStatus) &&
        Objects.equals(this.paymentType, expensePaymentStatusUpdatedEvent.paymentType) &&
        Objects.equals(this.companyId, expensePaymentStatusUpdatedEvent.companyId) &&
        Objects.equals(this.amount, expensePaymentStatusUpdatedEvent.amount) &&
        Objects.equals(this.paymentDescription, expensePaymentStatusUpdatedEvent.paymentDescription) &&
        Objects.equals(this.cardId, expensePaymentStatusUpdatedEvent.cardId)&&
        Objects.equals(this.additionalProperties, expensePaymentStatusUpdatedEvent.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventType, expenseId, paymentStatus, paymentType, companyId, amount, paymentDescription, cardId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpensePaymentStatusUpdatedEvent {\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    expenseId: ").append(toIndentedString(expenseId)).append("\n");
    sb.append("    paymentStatus: ").append(toIndentedString(paymentStatus)).append("\n");
    sb.append("    paymentType: ").append(toIndentedString(paymentType)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    paymentDescription: ").append(toIndentedString(paymentDescription)).append("\n");
    sb.append("    cardId: ").append(toIndentedString(cardId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("event_type");
    openapiFields.add("expense_id");
    openapiFields.add("payment_status");
    openapiFields.add("payment_type");
    openapiFields.add("company_id");
    openapiFields.add("amount");
    openapiFields.add("payment_description");
    openapiFields.add("card_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("event_type");
    openapiRequiredFields.add("expense_id");
    openapiRequiredFields.add("payment_status");
    openapiRequiredFields.add("payment_type");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExpensePaymentStatusUpdatedEvent
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExpensePaymentStatusUpdatedEvent.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpensePaymentStatusUpdatedEvent is not found in the empty JSON string", ExpensePaymentStatusUpdatedEvent.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ExpensePaymentStatusUpdatedEvent.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("expense_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expense_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expense_id").toString()));
      }
      if ((jsonObj.get("company_id") != null && !jsonObj.get("company_id").isJsonNull()) && !jsonObj.get("company_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `company_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("company_id").toString()));
      }
      // validate the optional field `amount`
      if (jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull()) {
        ExpensePaymentStatusUpdatedEventAmount.validateJsonObject(jsonObj.getAsJsonObject("amount"));
      }
      if ((jsonObj.get("payment_description") != null && !jsonObj.get("payment_description").isJsonNull()) && !jsonObj.get("payment_description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payment_description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payment_description").toString()));
      }
      if ((jsonObj.get("card_id") != null && !jsonObj.get("card_id").isJsonNull()) && !jsonObj.get("card_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("card_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpensePaymentStatusUpdatedEvent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpensePaymentStatusUpdatedEvent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpensePaymentStatusUpdatedEvent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpensePaymentStatusUpdatedEvent.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpensePaymentStatusUpdatedEvent>() {
           @Override
           public void write(JsonWriter out, ExpensePaymentStatusUpdatedEvent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpensePaymentStatusUpdatedEvent read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExpensePaymentStatusUpdatedEvent instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpensePaymentStatusUpdatedEvent given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpensePaymentStatusUpdatedEvent
  * @throws IOException if the JSON string is invalid with respect to ExpensePaymentStatusUpdatedEvent
  */
  public static ExpensePaymentStatusUpdatedEvent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpensePaymentStatusUpdatedEvent.class);
  }

 /**
  * Convert an instance of ExpensePaymentStatusUpdatedEvent to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

