/*
 * Webhooks API
 *  Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage. Use webhook subscriptions to subscribe to different webhook events. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets UpdateWebhookSubscriptionStatus
 */
@JsonAdapter(UpdateWebhookSubscriptionStatus.Adapter.class)public enum UpdateWebhookSubscriptionStatus {
  
  ACTIVE("ACTIVE"),
  
  INACTIVE("INACTIVE");

  private String value;

  UpdateWebhookSubscriptionStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UpdateWebhookSubscriptionStatus fromValue(String value) {
    for (UpdateWebhookSubscriptionStatus b : UpdateWebhookSubscriptionStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<UpdateWebhookSubscriptionStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final UpdateWebhookSubscriptionStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public UpdateWebhookSubscriptionStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return UpdateWebhookSubscriptionStatus.fromValue(value);
    }
  }
}

